/* eslint-disable no-console */
// MIT License

// Copyright (c) 2021 freeverse.io

// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:

// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.

// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

const identity = require('freeverse-crypto-js');
const { digestBuyNow, sign } = require('freeverse-marketsigner-js');
const argv = require('minimist')(process.argv.slice(2), {
  string: [
    'pvk',
    'buynowId',
    'buyerId',
    'currencyId',
    'price',
    'sellerRnd',
    'validUntil',
    'assetId',
  ],
});

const {
  pvk,
  buynowId,
  buyerId,
  currencyId,
  price,
  sellerRnd,
  validUntil,
  assetId,

} = argv;

const checkArgs = () => {
  const OK = (pvk
    && buynowId && buyerId && currencyId && price && sellerRnd && validUntil && assetId);
  if (!OK) {
    console.log(`
    ---------------
    Usage Example: 
    node create_buy_now_payment.js --pvk '0xd2827f4c3778758eb51719a698464aaffd10a5c7cf816c1de83c5e446bfc8e8d' --buynowId '0x81d6b8596f19fbf11f9484642cfb18e4763149ed1eabe5d514007e3d16b89399' --buyerId '0xD5f3608ab97D5bF16e5Eb2aCE608d04E4F0449F9' --currencyId 0 --sellerRnd 234124 --price 100 --validUntil '1632395810' --assetId '36771977682424071759165601888702044610709221343463'
    ---------------

    params:
    * pvk: the private key of the buyer
    * buynowId: the id of the buynow that this payment refers to
    * price: the price of the buynow, in units of cents of EUR
    * sellerRnd: a random number, generated by the seller of the asset when creating the buynow
    * buyerId: the id of the buyer
    * currencyId: currency 0: EUR
    * validUntil: when the buynow that buynowId refers to will end (Thursday, 23 September 2021 11:16:50)
    * assetId
    `);
  }
  return OK;
};

const run = () => {
  const digest = digestBuyNow({
    assetId,
    currencyId,
    price,
    sellerRnd,
    validUntil,
  });

  // create web3 account from your private key
  // (other forms of creating web3 account could be subsituted)
  const buyerAccount = identity.accountFromPrivateKey(pvk);
  const signature = sign({ digest, web3account: buyerAccount });
  const signatureToSend = signature.substring(2, signature.length);

  // inject results into final mutation to send to graphQL endpoint
  const assetMutation = `
mutation { 
  createBuyNowPayment(
    input: { 
      signature:"${signatureToSend}",
      buyNowId:"${buynowId}",
      buyerId: "${buyerAccount.address}",
      assetsPropsHash:"",
      price: ${price},
      rnd: ${sellerRnd}
      assetId: "${assetId}",
      currencyId: ${currencyId},
      validUntil: "${validUntil}",
    }
  )
}`;

  console.log(assetMutation);
};

const OK = checkArgs();
if (OK) run();
